version: '3'

services:
#  app:
#    build: .
#    ports:
#      - 8080:8080

  db-master:
    image: "postgres"
    env_file:
      - docker/database.env
    ports:
      - 5000:5432
    volumes:
      - ./docker/db-master-init.sql:/docker-entrypoint-initdb.d/init.sql

  db-tenant1:
    image: "postgres"
    env_file:
      - docker/database.env
    ports:
      - 5001:5432
    volumes:
      - ./docker/db-tenant1-init.sql:/docker-entrypoint-initdb.d/init.sql
