version: '3'

services:
#  app:
#    build: .
#    ports:
#      - 8080:8080

  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
