app:
  database:
    master:
      url: jdbc:postgresql://db-master:5432/app
      driver-class: org.postgresql.Driver
      username: root
      password: password
      show-sql: true
      format-sql: true
      ddl-auto: none
    tenant:
      show-sql: true
      format-sql: true
      ddl-auto: none
