app:
  database:
    master:
      url: jdbc:postgresql://db-master:5432/app
      driver-class: org.postgresql.Driver
      username: root
      password: password
      show-sql: true
      format-sql: true
      ddl-auto: none
    tenant:
      show-sql: true
      format-sql: true
      ddl-auto: none
---
spring:
  profiles: integration-test
app:
  database:
    master:
      url: jdbc:h2:mem:test
      driver-class: org.h2.Driver
      username: sa
      password:
      show-sql: true
      format-sql: true
      ddl-auto: validate
    tenant:
      show-sql: true
      format-sql: true
      ddl-auto: create
